### ISSUE TITLE
have a plan to support jsx in setup?

### ISSUE THREAD

**Issue by xu455255849** [vuejs/composition-api#896] opened 2022-01-26 03:37 UTC
when I refactor vue2 code to @vue/composition-api ,but jsx render is not work, like this:
![image](https://user-images.githubusercontent.com/15166243/151100048-59a55d78-2d29-476c-85e6-8596f800fedc.png)

**Comment by antfu** [comment] 2022-01-26 14:43
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-01-26 14:43 UTC
