### ISSUE TITLE
Type error using createComponent in a view imported to Router

### ISSUE THREAD

**Issue by ux-engineer** [vuejs/composition-api#193] opened 2019-11-19 11:13 UTC
Type error using createComponent function (using TypeScript) in a view component that is imported to Router:

```bash
21:30 Argument of type '{ mode: "history"; base: any; routes: ({ path: string; name: string; component: { name: string; components: { HelloWorld: VueConstructor<{ msg: string; } & Vue>; }; }; } | { path: string; name: string; component: VueProxy<...>; })[]; }' is not assignable to parameter of type 'RouterOptions'.    
  Types of property 'routes' are incompatible.
    Type '({ path: string; name: string; component: { name: string; components: { HelloWorld: VueConstructor<{ msg: string; } & Vue>; }; }; } | { path: string; 
name: string; component: VueProxy<ComponentPropsOptions<Data>, {}>; })[]' is not assignable to type 'RouteConfig[]'.
      Type '{ path: string; name: string; component: { name: string; components: { HelloWorld: VueConstructor<{ msg: string; } & Vue>; }; }; } | { path: string; name: string; component: VueProxy<ComponentPropsOptions<Data>, {}>; }' is not assignable to type 'RouteConfig'.
        Type '{ path: string; name: string; component: VueProxy<ComponentPropsOptions<Data>, {}>; }' is not assignable to type 'RouteConfig'.
          Types of property 'component' are incompatible.
            Type 'VueProxy<ComponentPropsOptions<Data>, {}>' is not assignable to type 'VueConstructor<Vue> | ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> | AsyncComponentPromise<...> | AsyncComponentFactory<...> | undefined'.  
              Type 'ComponentOptions<Vue, {}, never, never, ComponentPropsOptions<Data>, ExtractPropTypes<ComponentPropsOptions<Data>, false>> & VueConstructorProxy<ComponentPropsOptions<Data>, {}>' is missing the following properties from type 'VueConstructor<Vue>': extend, nextTick, set, delete, and 9 more.
    19 | ]
    20 | 
  > 21 | const router = new VueRouter({
       |                              ^
    22 |   mode: 'history',
    23 |   base: process.env.BASE_URL,
    24 |   routes
Version: typescript 3.5.3
```

Minimal bug reproduction repo: https://github.com/ux-engineer/bug-composition-api-createcomponent-with-router

**Comment by posva** [comment] 2019-11-19 18:58
Duplicate of https://github.com/vuejs/composition-api/issues/185

**Closed by posva** 2019-11-19 18:58 UTC
