### ISSUE TITLE
在vue2.6中使用这个，报错The setup binding property "addCount" is already declared.

### ISSUE THREAD

**Issue by Guidozijef** [vuejs/composition-api#954] opened 2022-07-15 03:08 UTC
在vue2.6中使用这个，报错The setup binding property "addCount" is already declared，setup函数导出的每一个属性都会有一个警告，这是为什么？

**Comment by antfu** [comment] 2022-07-15 03:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-15 03:23 UTC

**Comment by Cynthiafan** [comment] 2022-07-20 03:20
I got the same problem. I created a new project by vue cli and installed composition API, then encountered the situation.

https://codesandbox.io/s/composition-api-setup-problem-eigr1t?file=/src/App.vue
