### ISSUE TITLE
有关 <script setup></script>问题

### ISSUE THREAD

**Issue by mhxy13867806343** [vuejs/composition-api#905] opened 2022-02-15 08:34 UTC
无法使用

<script setup>
 onLoad(()=>{
 ....
 
 })

</script>
如何解决下

**Comment by antfu** [comment] 2022-02-16 12:42
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-02-16 12:42 UTC
