### ISSUE TITLE
attrs is not reactive when destructured

### ISSUE THREAD

**Issue by fer22f** [vuejs/composition-api#264] opened 2020-02-26 13:29 UTC
Minimal (non-)working example:
```vue
<template>
  <div>
    {{ $attrs['hello-world'] }}
    {{ myComputed }}
  </div>
</template>

<script>
import { defineComponent, computed } from "@vue/composition-api";

export default defineComponent({
  inheritAttrs: false,

  setup(props, { attrs }) {
    const myComputed = computed(() => attrs['hello-world']);

    return {
      myComputed
    }
  }
});
</script>
```

```vue
<template>
    <Example :hello-world="test"/>
   <button @click="change">Change me</button>
</template>

<script>
import { defineComponent, ref } from "@vue/composition-api";

import Example from "@/components/Example.vue";

export default defineComponent({
  components: { Example },

  setup() {
    const test = ref("Hey");

    return {
      change() {
        test.value = "What?";
      },
      test
    }
  }
});
</script>
```

The value in the template, `$attrs` changes accordingly, but the computed value doesn't.

**Comment by fer22f** [comment] 2020-02-26 14:44
Ok, solved this by **not** destructuring the context parameter. Lesson learned, but I wish the docs didn't send me into the wrong direction, this is really not correct:

---

`attrs` and `slots` are proxies to the corresponding values on the internal component instance. This ensures they always expose the latest values even after updates so that we can destructure them without worrying accessing a stale reference:

```ts
const MyComponent = {
  setup(props, { attrs }) {
    // a function that may get called at a later stage
    function onClick() {
      console.log(attrs.foo) // guaranteed to be the latest reference
    }
  }
}
```

**Comment by LinusBorg** [comment] 2020-02-28 12:56
Seems to be a bug, rather than a docs issue. But I still need to verify it though as you didn't provide runnable code.

The docs definitely decribe the intended behaviour, and `context.attrs` indeed a proxy wrapping `vm.$attrs`, so it *should* be reactive:

**Comment by superbiche** [comment] 2020-04-20 16:05
I'm having the exact same issue when I'm destructuring props: 
```javascript
// Composable that changes vuex state
async function deleteProviderFile(id) {
    try {
      await $api.delete(`providers/${currentProviderId.value}/files/${id}`)
     // I see the mutation happen in Vuex devtools
      return getProviderField('files').value = getProviderField('files')
        .value
        .filter(f => f.id !== id)
    } catch (e) {
      // TODO error alert
    }
  }

// component destructuring props: removing a picture doesn't update the rendered pictures
setup({ pictures }) {
      const state = reactive({
        featuredPicture: computed(() => pictures[0]),
        firstPictures: computed(() => pictures.slice(1, 5)),
        otherPictures: computed(() => pictures.slice(5)),
      })

      return {
        state,
      }
    },

// without destructuring: the UI updates accordingly
setup(props) {
      const state = reactive({
        featuredPicture: computed(() => props.pictures[0]),
        firstPictures: computed(() => props.pictures.slice(1, 5)),
        otherPictures: computed(() => props.pictures.slice(5)),
      })

      return {
        state,
      }
    },
```

I'm sorry if there's a more relevant issue, it's actually this one that led me to try without destructuring and fixed my months old bug (which I thought was a brain bug of mine).

**Comment by LinusBorg** [comment] 2020-04-20 17:01
Destructuring props is indeed not supported in that way. You would have to call `toRefs()` on it.

That's explained in the RFC I think

**Comment by superbiche** [comment] 2020-04-20 17:07
I was somehow expecting such an answer where I would have badly read either the docs here or the RFC. Very sorry :sweat_smile: and thanks a lot for replying despite my lack of attention!

**Comment by valgeirb** [comment] 2020-09-14 15:08
@antfu Can I ask why this was closed? This is still an issue as far as I know.

**Comment by posva** [comment] 2020-09-14 15:23
This is expected behavior as pointed out in the last comments ⬆️

**Comment by valgeirb** [comment] 2020-09-14 15:38
The last comments were in relation to ```props``` - but losing reactivity when destructuring ```context``` is still a bug.

**Comment by antfu** [comment] 2020-09-14 16:02
Sorry, I missed reading the issue so I closed it. However, just like Linus pointed out in this comment https://github.com/vuejs/composition-api/issues/264#issuecomment-592500909, there is no clear way to solve this as destructuring context will break the proxy to `vm.$attrs`. Maybe I could add it to the limitation of the README. What do you think?

**Comment by valgeirb** [comment] 2020-09-14 16:15
Yeah that might be a good idea if this can't be solved. Not to be confrontational, but are you fine with this package not mirroring the functionality of the Vue 3 composition API?

**Comment by 9-lives** [comment] 2020-11-22 08:53
Please don't close this issue because VCA official doc mentioned that `attrs and slots are proxies to the corresponding values on the internal component instance` .
I just spent 1 hour on figuring it out. Maybe a little tip in readme would be better?

**Closed** 2020-12-07 13:45 UTC
Labels: bug

**Comment by m4heshd** [comment] 2021-02-24 18:35
@antfu why doesn't it have the same functionality on Vue 3? It's still not reactive.
