### ISSUE TITLE
Wrapping custom types in a ref breaks type inference

### ISSUE THREAD

**Issue by aaf-ww** [vuejs/composition-api#179] opened 2019-11-04 16:50 UTC
Typing a variable like so:
```ts
const foo: Ref<string[]> = ref(stringArray)
```
works fine and if the contents of stringArray aren't string[] then vscode shows a visible error.

However, if I create a ref with a custom type like this:
```ts
interface ComplexType {
  name: string;
  data: "value1" | "value2" | "value3" | "etc";
}
const foo: Ref<ComplexType[]> = ref(complexArray)
```
I can give the data property any string value and it doesn't complain.

**Comment by LinusBorg** [comment] 2019-11-05 08:18
This works for me:

![code](https://user-images.githubusercontent.com/1444526/68190151-29f72a80-ffad-11e9-8bda-48ef5e4ebda3.gif)

**Comment by aaf-ww** [comment] 2019-11-05 15:39
Yes, that does appear to work but if I were to change the value in the ref to "value4" then TypeScript sees that as a valid value. Is that supposed to work that way?

**Comment by lmiller1990** [comment] 2019-12-27 00:31
I have the same problem as the original example - I am allowed to initialize a ref with a invalid value. It does prevent reassigning `.value` correctly, though.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/19196536/71494599-02795b80-2894-11ea-8b44-d5ed0f1500eb.png">

**Comment by wyzgo** [comment] 2020-01-13 02:47
I have the same problem, have you solved it? @lmiller1990

**Comment by lmiller1990** [comment] 2020-01-13 03:11
I haven't look into this yet... I can take a look sometime this week. I guess it something around here needs to be changed: https://github.com/vuejs/composition-api/blob/e1b9757d0695643ca940518ada986862c651efba/src/reactivity/ref.ts#L109

**Comment by antfu** [comment] 2020-06-11 16:06
This works fine in the latest version. I am closing this for now. If you still find the same issue, please feel free to reopen and providing a reproduce demo. Thanks!

**Closed by antfu** 2020-06-11 16:06 UTC

**Comment by dguay** [comment] 2021-08-09 17:50
Using 1.0.5 and this piece of code in `setup()` does not yield any typescript error:

```
const isLoading:Ref<boolean> = ref<boolean>('someString')
isLoading.value = 123
```
