### ISSUE TITLE
toRefs does not return the correct typescript type

### ISSUE THREAD

**Issue by lixpng** [vuejs/composition-api#232] opened 2020-01-19 02:38 UTC
If a Object type has a `value` attribute, after I use `toRefs(xxx)`, the `typescripte` type will incorrect. 
eg: 
```javascript
interface IObjectWithValueAttr {
    name: string
    value: string
}

interface IA {
    b: IObjectWithValueAttr
}

const a: IA = {
    b: {
        name: 'Jon',
        value: 'test'
    }
}

const refsA = toRefs(a)

// there will is a error, because refsA.b will be infer to type `Ref<string>`
refsA.b.name = 'Tony'
```
Is it because the `Ref` interface only define the `value` key ?

**Comment by jacekkarczmarczyk** [comment] 2020-01-19 02:53
https://github.com/vuejs/composition-api/pull/199

**Comment by posva** [comment] 2020-01-19 09:40
Let's close this as a duplicate of https://github.com/vuejs/composition-api/issues/157

**Closed by posva** 2020-01-19 09:40 UTC
