### ISSUE TITLE
Watched Previous Values can't be Destructure on First Fire

### ISSUE THREAD

**Issue by klondikemarlen** [vuejs/composition-api#418] opened 2020-06-30 18:40 UTC
When? watching an array of values I can't destructure the previous values on the initial loop run.
Why? the previous values are returned as `undefined`.
What I expect? I expect the previousValue on initial run to be equal to `[undefined, undefined]` so I can destructure it properly.

Code I have to write:
```javascript
watch(
  () => [unref(unitId), unref(entityType)],
  ([newUnitId, newEntityType], oldValues) => {
    const [oldUnitId, oldEntityType] = oldValues || [undefined, undefined]

    if (!newUnitId || !newEntityType) return
    if (
      entitySchemaState.entitySchema &&
      newUnitId === oldUnitId &&
      newEntityType === oldEntityType
    )
      return

    fetch()
  },
  { immediate: true }
)
```

Code I want to write:
```javascript
watch(
  () => [unref(unitId), unref(entityType)],
  ([newUnitId, newEntityType], [oldUnitId, oldEntityType]) => {
    if (!newUnitId || !newEntityType) return
    if (
      entitySchemaState.entitySchema &&
      newUnitId === oldUnitId &&
      newEntityType === oldEntityType
    )
      return

    fetch()
  },
  { immediate: true }
)
```

**Comment by pikax** [comment] 2020-07-03 08:22
That's the same behaviour as you have in vue3.

AFAIK this is the expected behaviour since you are deconstructing an `undefined`.

**Comment by antfu** [comment] 2020-07-03 09:02
@klondikemarlen This should works for you

```ts
watch(
  [unitId, entityType],
  ([newUnitId, newEntityType], [oldUnitId, oldEntityType]) => {

  }
)
```

**Comment by antfu** [comment] 2020-07-04 10:59
Hope it solves your problem. Closing for now.

**Comment by klondikemarlen** [comment] 2020-07-04 15:43
I know that I can't destructing an undefined. :P

I want the watch function to _always_ return an array if it is operating on an array of args.

**Comment by klondikemarlen** [comment] 2020-07-04 15:52
> @klondikemarlen This should work for you
> 
> ```ts
> watch(
>   [unitId, entityType],
>   ([newUnitId, newEntityType], [oldUnitId, oldEntityType]) => {
> 
>   }
> )
> ```

When I try passing in an array instead of a function, I get the same destructuring error.
![image](https://user-images.githubusercontent.com/23045206/86516200-6b0d3c00-bdd3-11ea-8758-bb2066d60802.png)

**Comment by antfu** [comment] 2020-07-04 15:58
I will have a look

**Comment by MrDenexi** [comment] 2020-07-20 12:16
If this is expected behaviour, then I suggest updating [the documentation](https://composition-api.vuejs.org/api.html#watch) to make it more clear. It is a bit confusing to get an error after using the 'Watching Multiple Sources'-example.

**Closed** 2021-06-17 19:30 UTC
Labels: misalignment
