### ISSUE TITLE
$refs（DOM） cannot be assigned  ref

### ISSUE THREAD

**Issue by GTRgoSky** [vuejs/composition-api#673] opened 2021-04-08 09:29 UTC
I've got a problem，When I click test, c is null.
UpdateTemplateRef does not update the parent's **ref**  because the slot is a function and the parent does not need to be updated when PV updates slot.

code：
```js
// parent.vue
    <PV>
        <div @click="test">222</div>
        <template #left>
            <div v-if="i" ref="c">111</div>
        </template>
    </PV>
// script
setup() {
    const c = ref(null);
    const i = ref(false);
    
    function test () {
        i.value = true;
       console.log(c.value) // null
    }
}

// PV.vue
<template>
    <div class="pp">
        <div class="left">
            <slot name="left"></slot>
        </div>
        <slot></slot>
    </div>
</template>
```

**Comment by pikax** [comment] 2021-04-10 09:14
Duplicate of https://github.com/vuejs/composition-api/issues/296

**Closed by pikax** 2021-04-10 09:14 UTC
