### ISSUE TITLE
Proxying events  with v-on="computed"

### ISSUE THREAD

**Issue by timshannon** [vuejs/composition-api#128] opened 2019-09-11 20:44 UTC
I'm trying to replicate the proxying of events as described here: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components in the composition api.  But am unable to get the events to proxy like they do without the plugin.

```typescript
<label>
{{ label }}
    <input
        v-bind:value="value"
        v-on="inputListeners"
    >
</label>
export default createComponent({
    props: ["label", "value"],
    setup(props, context) {
        const inputListeners = computed(() => {
            // `Object.assign` merges objects together to form a new object
            return Object.assign({},
                // We add all the listeners from the parent
                context.root.$listeners,
                // Then we can add custom listeners or override the
                // behavior of some listeners.
                {
                    // This ensures that the component works with v-model
                    input: (event) => {
                        context.emit("input", event.target.value);
                    },
                },
            )
        });
        return {
            inputListeners,
        };
    },
});
```

Full fiddle here: https://jsfiddle.net/4wfzh0u6/

**Comment by liximomo** [comment] 2019-09-12 03:34
The event proxy works file in the fiddle.  What's your expectation?

**Comment by liximomo** [comment] 2019-09-16 06:17
```js
Object.assign({},
  // We add all the listeners from the parent
  context.root.$listeners, 
  // Then we can add custom listeners or override the
  // behavior of some listeners.
  {
    // This ensures that the component works with v-model
    input: function (event) {
      context.emit('input', event.target.value)
    },
  },
)
```

You should not use `context.root.$listeners`. 

![image](https://user-images.githubusercontent.com/9816225/64937151-baf23500-d88b-11e9-9a4b-d54cc4e9559e.png)

Unfortunately, we can't do this now because `this` is not available in `setup()`.

**Comment by LinusBorg** [comment] 2019-09-16 14:25
I think the problem is that there's not `context.listeners`. That's ok insofar as the RFC spec says that it doesn't, but that's only because, according to another RFC, `this.$listeners`  and `this.$attrs` will be merged in Vue 3.

@liximomo So  I think we should introduce a `context.listeners` property for this plugin - that would be in line with the spirit of the RFCs, as `context` should allow users to access these properties.

**Comment by liximomo** [comment] 2019-09-17 03:03
@LinusBorg I agreed.

**Closed** 2019-09-17 16:01 UTC
Labels: enhancement
