### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by turkyden** [vuejs/composition-api#949] opened 2022-07-04 13:50 UTC
貌似更新了新版的 @vue/composition-api 后报错了，求助大佬 ... @antfu 

```
@vue/composition-api: "^1.7.0"
vue: "^2.6.14",
```

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/24560160/177168117-a9fd65a0-5fa2-4bbc-bbf9-4863ed39365c.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/24560160/177167623-ec7cac53-bc3d-42aa-a895-bc344cf4c955.png">

**Comment by antfu** [comment] 2022-07-04 14:05
v1.7.0 changed nothing about the version range of Vue. https://github.com/vuejs/composition-api/commits/main

---

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-04 14:05 UTC

**Comment by zcqno1** [comment] 2022-07-15 02:53
Suffer from it too. 
Have a check on Vue version. Vue  has just published v2.7 with built-in composition api support.
