### ISSUE TITLE
Cannot import Vue Plugin using Composition API in my project

### ISSUE THREAD

**Issue by Warz** [vuejs/composition-api#372] opened 2020-06-12 01:05 UTC
A [project](https://github.com/Warz/nightterror) and a [plugin](https://github.com/Warz/vue-jstree).  The plugin contains Composition API functions that I want to consume in my project. My project is using Composition API already.

But, I can't figure out a way to import plugin in my project successfully. What I present below is the closest I've gotten. The script seems to work (?), but it's throwing warnings such as this;
`[Vue warn]: The setup binding property "multiTree" is already declared.`

index.js (in project)
```
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api';
Vue.use(VueCompositionApi);

import { VJstree } from 'vue-jstree-extended'

Vue.use(VJstree,{});

import App from './App.vue'
new Vue({
    el: '#app',
    render: h => h(App)
})
```
index.js (in plugin)
```
import VJstree from './tree.vue'
import useMultiTree from "./useMultiTree";
import useTreeActions from "./useTreeActions";
import VueCompositionApi from '@vue/composition-api'; // <---- get rid of this line

VJstree.install = function(Vue,options = {}){
  Vue.use(VueCompositionApi); // <---- get rid of this line
  Vue.component(VJstree.name, VJstree);
};

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(VJstree);
}

export { VJstree, useMultiTree, useTreeActions }

```

If I remove  `Vue.use(VueCompositionApi);` from plugin, I will get this error in my project:
`Error in data(): "Error: [vue-composition-api] must call Vue.use(plugin) before using any function."`

This doesn't make sense to me. I already called Vue.use(VueCompositionApi) in my project. The line shouldn't be required inside of plugin. Right?

Please note that the plugin is located in another folder, and I'm including it like this:
`    "vue-jstree-extended": "file:../jstree-extended-warz/vue-jstree"`

(I've also attempted using `npm link`, makes no difference)

I've read similar issues: #228 #340 #356 #181 which led me to discover peerDependencies, I've set up Composition API as a peerDependency in plugin.

I've also attempted to import both Vue and Composition API in the plugin, this results in the following error in project while performing actions in the tree:
`vue.esm.js:629 [Vue warn]: You may have an infinite update loop in a component render function.`

So the question is really, how can I get rid of Vue.use(VueCompositionApi) from my plugin?

Any ideas?

**Comment by pikax** [comment] 2020-06-12 07:35
> This doesn't make sense to me. I already called Vue.use(VueCompositionApi) in my project. The line shouldn't be required inside of plugin. Right?

You don't need to do it in the plugin, using it in the plugin might cause some difficult to spot issues.

> Please note that the plugin is located in another folder, and I'm including it like this:
"vue-jstree-extended": "file:../jstree-extended-warz/vue-jstree"

The issue is here. 

When you are using composition API you need to **guarantee**  you are using the same plugin instance! 
Usually your bundler will just resolved it easily in your `node_modules`, but when you link or import from a local folder, your imported `node_modules` takes priority than your project, if `@vue/composition-api` is installed there it will use that instance, making you have two different composition-api plugins.

**Comment by Warz** [comment] 2020-06-12 10:55
Instance? Or do you mean version? I'm pretty confused right now. I have the same version of Composition API across the board and there should only be one instance set in Vue, it's being set in my project. 

Right now I'm only running Vue.use(VueCompositionApi) inside the project and that results in this error:
Error: [vue-composition-api] must call Vue.use(plugin) before using any function

I even tried to delete `node_modules` folder from my plugin (vue-jstree), no dice.

How do I go about fixing this? I need to be able to do local development so I can quickly test changes I make in my plugin.

**Comment by antfu** [comment] 2020-06-12 12:31
Hi @Warz , can you share a minimal reproduce repo (best in codesandbox) so we can better help your problem? Thanks.

**Comment by Warz** [comment] 2020-06-12 14:20
I hope this is simple enough:
https://github.com/Warz/issue372

See instructions in README.md. 

I wasn't sure how I'd do this in codesandbox.

**Comment by pikax** [comment] 2020-06-12 16:43
![image](https://user-images.githubusercontent.com/4620458/84525845-362a2f80-acd4-11ea-9fff-6b68c3cedb96.png)

seems to be working to me, I'm using `yarn`

**Comment by Warz** [comment] 2020-06-13 00:14
Yes, you are correct. I have not tried yarn, but i'd really like to make this work with npm as well. 

The only place importing composition api is in the functions, for example here is useMultiTree.js from the plugin
```
import { reactive } from '@vue/composition-api';

export default function useMultiTree() {

    const state = reactive({
        currentDraggedNode : null,
    });

    function setDraggedNode(node) {
        state.currentDraggedNode = node;
    }

    function isDragging() {
        return !!state.currentDraggedNode;
    }

    return {
        state,
        isDragging,
        setDraggedNode
    }
}
```
If I comment out the import line from useMultiTree.js and useTreeActions.js I'm not getting the console.log output for the plugin composition api node_modules, but obviously that breaks the functions. 

Any idea how I would go about fixing this? I tried setting resolve alias in the project webpack to force it to use the one in my project:
```
    resolve: {
        symlinks: false,
        alias: {
            '@vue/composition-api': path.resolve(path.join(__dirname, '../node_modules/@vue/composition-api/'))
        }
    }
```
but didn't make any difference. 

Maybe there's some documentation detailing this specific issue?

**Comment by pikax** [comment] 2020-06-13 08:23
That's a module resolver issue , either `webpack` or `npm`, the solution for this problem is making sure you only import the same `@vue/composition-api`, how you can do it is quite dependent on the tools you use. Unfortunately I don't know how to achieve that with webpack and npm (with localImport)

I'm surprised `yarn` worked. 

If you find a solution please share here.

**Comment by darrenjennings** [comment] 2020-06-22 19:23
>  I tried setting resolve alias in the project webpack to force it to use the one in my project:

@Warz FWIW your alias resolve fixed it for me. my vue.config is is in the same dir as my node_modules btw
```diff
- '@vue/composition-api': path.resolve(path.join(__dirname, '../node_modules/@vue/composition-api/'))
+ '@vue/composition-api': path.resolve(path.join(__dirname, './node_modules/@vue/composition-api/'))
```

**Comment by Warz** [comment] 2020-06-23 20:11
I'm using webpack, changing to that just results in error
`Module not found: Error: Can't resolve '@vue/composition-api'`

Can you post full code?

**Comment by antfu** [comment] 2020-07-04 11:01
BTW, have a look at [vue-demi](https://github.com/antfu/vue-demi) :)

**Comment by Warz** [comment] 2020-07-05 21:32
Thanks for fix. I've upgraded to 1.0.0-beta.2, but now I'm getting some different errors:
![chrome_2020-07-05_23-18-18](https://user-images.githubusercontent.com/245580/86542613-63ef4680-bf17-11ea-8109-4bdfb3890dd4.png)

Any ideas? Do I need to do any specific changes to make it work?

**Comment by antfu** [comment] 2020-07-06 01:44
Can you update your code to the repo and share again? Thanks

**Comment by Warz** [comment] 2020-07-06 17:49
I've now [comitted](https://github.com/Warz/issue372/commit/88fc956a25a95d96def03e611bf2debfcfe49b94) the latest changes 

Running `npm run build` in the plugin folder and `npm run dev` in the project folder

**Comment by ymchun** [comment] 2020-07-10 08:33
> Thanks for fix. I've upgraded to 1.0.0-beta.2, but now I'm getting some different errors:
> ![chrome_2020-07-05_23-18-18](https://user-images.githubusercontent.com/245580/86542613-63ef4680-bf17-11ea-8109-4bdfb3890dd4.png)
> 
> Any ideas? Do I need to do any specific changes to make it work?

I have the same issue when using composition api in my plugin and imported to my project. It work without any problems when the plugin components are inside my project.

Suspect the issue is due to different instance of composition api. The following code is how I export the plugin inside `index.ts`

```typescript
import { VueConstructor } from 'vue'

import ColumnSectionItem from './components/column-section-item.vue'
import DynamicForm from './components/dynamic-form.vue'
import RowSectionItem from './components/row-section-item.vue'

export default {
  install(_vue: VueConstructor) {
    _vue.component('ColumnSectionItem', ColumnSectionItem)
    _vue.component('DynamicForm', DynamicForm)
    _vue.component('RowSectionItem', RowSectionItem)
  },
}
```

**Comment by antfu** [comment] 2020-07-10 17:01
@Warz you are packing @vue/composition-api into your plugin - which you shouldn't. Closing for now.

**Closed by antfu** 2020-07-10 17:01 UTC

**Comment by Warz** [comment] 2020-07-10 17:15
> @Warz you are packing @vue/composition-api into your plugin - which you shouldn't. Closing for now. Thanks

What do you mean? I've set it as a peer dependency?

**Comment by antfu** [comment] 2020-07-10 18:21
https://webpack.js.org/configuration/externals/

**Comment by Warz** [comment] 2020-07-10 20:48
Like this ? [*](https://github.com/Warz/issue372/commit/d420824dbb66186cf0714953e674b3407390ba09)
```
  module.exports.externals = {
      '@vue/composition-api': 'commonjs2 @vue/composition-api'
  }
```


Doing that put me back at this point:
```
vue.runtime.esm.js:620 [Vue warn]: Error in data(): "Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function."

found in

---> <App> at src/App.vue
       <Root>
```

**Comment by ymchun** [comment] 2020-07-11 15:11
> Like this ? [*](https://github.com/Warz/issue372/commit/d420824dbb66186cf0714953e674b3407390ba09)
> 
> ```
>   module.exports.externals = {
>       '@vue/composition-api': 'commonjs2 @vue/composition-api'
>   }
> ```
> 
> Doing that put me back at this point:
> 
> ```
> vue.runtime.esm.js:620 [Vue warn]: Error in data(): "Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function."
> 
> found in
> 
> ---> <App> at src/App.vue
>        <Root>
> ```

```javascript
module.exports = {
  chainWebpack: config => {
    config.merge({
      externals: ['vue', '@vue/composition-api'],
    })
  },
}
```

**Comment by oneMoreTime1357** [comment] 2021-05-13 09:02
add '@vue/composition-api' to webpack externals solve my problem;

**Comment by xieqian423** [comment] 2021-08-11 10:05
![image](https://user-images.githubusercontent.com/5831943/129010700-c4e2a2c6-4876-4fca-b8d4-8e159ed83c4d.png)
编译后报错[vue-composition-api]no vue dependency found
