### ISSUE TITLE
Variables created with ref in <templete>,do not automatically expand value

### ISSUE THREAD

**Issue by Raoting1997** [vuejs/composition-api#956] opened 2022-08-02 06:48 UTC
Vue version is `V2.6.14`.

 example code:
```JavaScript
<template>
    <div id="app">
        {{ test }}
    </div>
</template>
import { ref } from '@vue/composition-api';

export default {
    name: 'App',
    setup() {
        const test = ref('test');
        return { test };
    }
};
```

The result of `test` on the page is `{ value: 'test'}`,not `test`.

`computed` too.

Please pay attention to this problem

**Comment by CNMathon** [comment] 2022-08-04 09:00
I encountered, too.

**Comment by CNMathon** [comment] 2022-08-04 09:29
@antfu Is there a schedule for repairs?

**Comment by antfu** [comment] 2022-08-04 11:13
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-04 11:13 UTC
