### ISSUE TITLE
Need access to $refs in SetupContext

### ISSUE THREAD

**Issue by jorgy343** [vuejs/composition-api#226] opened 2020-01-09 04:34 UTC
I understand that `$refs` is no longer accessible in the setup context (`SetupContext`) and you are supposed to use the `ref` type instead. I have a need to pass all of the `$refs` to a function so that the function can apply error messages received from the server to the correct elements.

```javascript
errorHelper.handleError(response.data, context.refs);
```

It would be useful to still have access to refs and stress that the preferred way of accessing refs is through the `ref` type.

**Comment by jorgy343** [comment] 2020-01-09 05:22
I noticed that `refs` is still part of the `SetupContext` object so I created the following .d.ts file.

```javascript
import { SetupContext } from '@vue/composition-api';

declare module '@vue/composition-api/dist/component/component' {
  interface SetupContext {
    refs: any;
  }
}
```

I'm not sure what type `refs` should be.

**Comment by LinusBorg** [comment] 2020-01-09 15:47
I'm still getting accustomed to TS, but: I'd just keep it at `any` and then typecast it where you actually use it.Something like:

```typescript
import MyComponent from './myComponent.vue'
interface MyRefs {
  refname1: HTMLElement
  refname2: InstanceType<MyComponent>
}
 // ...
setup(_, { refs }) {
 // ...
  errorHelper.handleError(response.data, context.refs as MyRefs);
}
```

**Comment by sduduzog** [comment] 2020-02-07 19:39
I also just ran accross to this issue. Hopefully it will be taken care of in v3 of Vuejs. for now I think it's fair to use @jorgy343 's solution

**Comment by LinusBorg** [comment] 2020-02-07 20:29
In Vue 3, there will be no refs object in context as template refs can be used for all situations. As explained in this plugin's README, we provide it right now only because we can't use template ref functions in Vue 2, which we would need to collect refs in a v-for loop.

**Comment by sduduzog** [comment] 2020-02-08 00:19
@LinusBorg It all makes sense now. @jorgy343 @LinusBorg you don't need to pass  refs from context. Just create a variable with the exact same name as your ref value in your element.

 i.e. `const myRef = ref<your element type here>([])`

Check this out https://dev.to/sduduzog/creating-an-auto-resizing-textarea-with-vue-composition-api-in-4-easy-steps-i-can-t-wait-for-vuejs-v3-3n8l

**Comment by djkloop** [comment] 2020-04-26 09:11
```javascript
/// a.ts file
import YourXXXComponent from "./index.vue";
export type YourXXXRefs = InstanceType<typeof YourXXXComponent>

/// other vue file
import { YourXXXRefs } from "a.ts";

setup() {
 const viewRefs = ref<YourXXXRefs>("");
 // get refs props & methods
 onMounted(() => {
  console.log(viewRefs.value.xxxx)
 })

  return {
    viewRefs
  }
}

```

**Comment by gokhantaskan** [comment] 2020-04-27 15:21
> In Vue 3, there will be no refs object in context(*) as template refs can be used for all situations, and you can type those easily.
> ```ts
> const myRefs = ref<HTMLElement[]>([])
> ```
> 
> *: As explained in this plugin's README, we provide it right now only because we can't use template ref functions in Vue 2, which we would need to collect refs in a v-for loop.
----
```js
// apex.js
import Vue from "vue";
import VueApexCharts from "vue-apexcharts";

Vue.component("apexchart", VueApexCharts);
```
<apexchart /> is a global component and it is not working with the code below: 

```vue
// BarChart.vue
<template>
  <apexcharts ref="chartRef" ... />
</template>

<script lang="ts">
import { defineComponent, ref, reactive, toRefs, onMounted, watch } from "@vue/composition-api";

export default defineComponent({
  name: "...",
  props: {
    ...
  },
setup(props: OverviewChartProps, vm) {
  ...
  const chartRef = ref<HTMLElement[]>([]);
  ...
  chartRef.value.updateSeries([...series]);
  ...
});
```
> `vm.refs.chartRef` works when TS is not used.

The error is `Property 'updateSeries' does not exist on type 'HTMLElement[]'`.

```ts
const chartRef = ref<InstanceType<any>>([]); // works but not ideal at all.
```

**Comment by LinusBorg** [comment] 2020-04-27 15:55
Well, `<apexCharts>` is not an HTMLelement, its a component.

I can't tell you off the top of my head (on mobile right now) how to get the component type best, but think there should be a way.

**Comment by sseeland** [comment] 2020-06-15 13:03
Any update on this? I have the same problem and haven't found out how to get the right types for my component refs. I can get TypeScript to stop complaining by using `ref<typeof MyComponent>()`but I don't get proper autocomplete from this, so something must be wrong. 

Also, maybe related to this, I need access to my refs outside of `setup()` in my navigation guards. AFAIK the only way to implement `beforeRouteLeave` is "the old way" with the options syntax, at least that works for me. The hook gets executed and works as expected and I have access to `this`. I can even call `this.$refs.myComponent` and it works but TypeScript keeps throwing errors, as you would expect. And since `this.$refs` will go away in Vue 3 I don't really want to use it.

So, any ideas on how to properly type component refs and how to access them outside of `setup()`?

**Comment by antfu** [comment] 2020-06-22 07:38
How about:

```ts
declare module '@vue/composition-api' {
  interface SetupContext {
    readonly refs: { [key: string]: Vue | Element | Vue[] | Element[] };
  }
}
```

**Comment by sseeland** [comment] 2020-06-22 09:39
That does give access to refs inside the setup function, but I can access them with the standard `ref()` as well. That is not the problem. The problem is, that those refs are untyped, as are the refs returned by the interface extension you posted. When I try to call a method on my components, Typescript will complain.

```
import MyComponent from "@/components/mycomponent.vue";

export default defineComponent({
  setup() {
    const myComponent = ref<typeof MyComponent>();
    myComponent.value!.myFunction(); // gives type error: property 'myFunction' does not exist on Type VueProxy...
  }
});
```

So how do I get proper access to components? When I can cast them to HTMLElements everyhting is fine but I don't know how to cast them to my custom components.

Also, this doesn't help me in navigation guards. SetupContext is not available there, but neither is $refs. And even if it where, it would be untyped.

Of course I can "type" in my components, but that feels super hacky and unclean since it would be global. So I would have all my custom components type annotated in every SetupContext. Also, I still don't know how to actually type a component... `typeof MyComponent` doesn't help.

**Comment by sduduzog** [comment] 2020-06-22 11:45
Seems like the original issue is resolved. Can we close this one and create another specific to component ref types?

**Comment by sseeland** [comment] 2020-06-22 11:49
Fine by me, I'll open a new issue once I find the time to write it up nicely.

**Closed** 2020-06-22 12:52 UTC
Labels: documentation

**Comment by axe-me** [comment] 2020-10-21 15:19
> How about:
> 
> ```ts
> declare module '@vue/composition-api' {
>   interface SetupContext {
>     readonly refs: { [key: string]: Vue | Element | Vue[] | Element[] };
>   }
> }
> ```

where should I put this in? I added it to shims-vue.d.ts, but it breaks importing other stuff from the module: 
```
Module '"@vue/composition-api"' has no exported member 'defineComponent'
```

**Comment by danielroe** [comment] 2020-10-21 16:22
@axe-me To extend an interface you need at least one import in your declaration file.
