### ISSUE TITLE
vue2  computed  value not change when depend on a reactive array  

### ISSUE THREAD

**Issue by Hucy** [vuejs/composition-api#637] opened 2021-01-25 09:11 UTC
vue3 is ok  [vue3  demo](https://codesandbox.io/s/vue3-computed-reactive-array-ou3gf?file=/src/App.vue:341-349)

[vue2 demo](https://codesandbox.io/s/vue2-reactive-computed-array-6h0hc?file=/src/App.vue:277-285)

**Comment by tuomas2** [comment] 2021-03-08 16:49
Also watches (with `watch()`) do not work for reactive arrays.

**Comment by tuomas2** [comment] 2021-03-08 16:50
Related / duplicate of #521

**Comment by tuomas2** [comment] 2021-03-09 08:34
If reactive array is encapsulated within ref() then it works.

**Comment by iheyunfei** [comment] 2021-05-26 09:30
It's expected behaviors for current codes.  https://github.com/vuejs/composition-api/issues/581#issuecomment-848617944

**Closed** 2021-09-16 23:41 UTC
Labels: bug, no-issue-activity
