### ISSUE TITLE
Something wrong when I have 'value' in reactive object

### ISSUE THREAD

**Issue by xmsz** [vuejs/composition-api#250] opened 2020-02-13 07:12 UTC
![image](https://user-images.githubusercontent.com/5879146/74410096-3b38b880-4e73-11ea-84d8-ee4303b18067.png)

**Comment by LinusBorg** [comment] 2020-02-13 07:39
Screenshots like this are making it hard for us to understand what you mean.

And impossible t help you. 

Please provide actual code, and explain the problem

**Comment by jsmith** [comment] 2020-02-17 15:23
Pretty sure this is just a duplicate of #157

**Comment by xmsz** [comment] 2020-02-19 13:48
> Pretty sure this is just a duplicate of #157

Yes, Same issue

**Comment by LinusBorg** [comment] 2020-02-19 14:02
Then I'll close as a duplicate.

I think a PR addressing #157 is already in the works

**Closed by LinusBorg** 2020-02-19 14:02 UTC
Labels: not-reproducible
