### ISSUE TITLE
Array does not work with ref or reactive

### ISSUE THREAD

**Issue by vallemar** [vuejs/composition-api#581] opened 2020-11-01 18:45 UTC
If the value of an array is changed, the reactivity is not activated and the returned value is the old one.

- [KO-> vue 2 + composition api.](https://codesandbox.io/s/white-tdd-xqec2?file=/src/App.vue)
- [OK-> vue 3.](https://codesandbox.io/s/vigorous-gates-m5005?file=/src/App.vue)

**Comment by iheyunfei** [comment] 2021-05-26 09:28
It's because of limitation of Vue2 reactivity system. May have a way to hack this, but I think current behaviors is also expected.

`ref([1, 2])` works, but the way you are using is wrong in Vue2. check https://codesandbox.io/s/inspiring-heisenberg-sp7px 
`reactive([1, 2])` is not reactive, which is expected.

more details to see [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html) and vuejs/vue#9499
https://github.com/vuejs/composition-api/blob/30e3ddf63db49ff3023c529acc03fcac57d0069d/src/reactivity/reactive.ts#L108

Also duplicate of #521. @antfu maybe closes this one?

**Comment by iheyunfei** [comment] 2021-05-27 08:21
thinking back again, It's also worked with `reactive([])`, but with the limitation of Vu2 you need use `set` or `Vue.set` to set value on Array. 
see https://codesandbox.io/s/peaceful-rhodes-hpp6c?file=/src/App.vue

It's not a bug. sorry for my misunderstanding.

**Closed** 2021-09-16 23:41 UTC
Labels: no-issue-activity
