### ISSUE TITLE
Argument of type 'unknown' is not assignable to parameter of type 'Data'. 

### ISSUE THREAD

**Issue by sadjow** [vuejs/composition-api#460] opened 2020-08-06 04:27 UTC
When tryings to use the `props` first argument of `setup()` in a toRef, I am getting this error:

`Argument of type 'unknown' is not assignable to parameter of type 'Data'. `

***Version:** `"@vue/composition-api": "^1.0.0-beta.6",`*

![image](https://user-images.githubusercontent.com/177525/89490641-b5dbf400-d783-11ea-8366-11faddc3ad7e.png)

**Comment by sadjow** [comment] 2020-08-06 04:31
Also, when using `toRef` I get a `Argument of type 'unknown' is not assignable to parameter of type 'object'`
![image](https://user-images.githubusercontent.com/177525/89490954-7bbf2200-d784-11ea-9f8f-776eb341a8df.png)

**Comment by posva** [comment] 2020-08-06 06:49
Can you provide at least the text version of the whole component ? You probably have a typing problem in your props making them unknown

**Comment by sadjow** [comment] 2020-08-06 06:57
@posva Here we go. See my temp solution on line `const processing = toRef(props as any, "processing");`
```vue
<template lang="pug">
  b-button(v-bind="$props" @click="onClick" :disabled="processing || internalProcessing")
    template(v-if="processing || internalProcessing")
      b-spinner(small)
      |  {{ processingText }}
    template(v-else)
      slot
</template>

<script lang="ts">
import { defineComponent, ref, toRef, watch } from "@vue/composition-api";

import { BButton } from "bootstrap-vue/esm/components/button/button";
// Make a copy of b-button's prop definitions
const btnProps = Object.assign({}, BButton.options.props);

export default defineComponent({
  components: {
    BButton,
  },
  props: {
    ...btnProps,
    processing: {
      type: Boolean,
      default: false,
    },
    processingText: {
      type: String,
      default: "Processing...",
    },
  },
  setup(props, { emit }) {
    const internalProcessing = ref(false);

    const processing = toRef(props as any, "processing");

    watch(
      () => processing.value,
      (isProcessing) => {
        if (!isProcessing) {
          internalProcessing.value = false;
        }
      }
    );

    function onClick() {
      internalProcessing.value = true;
      setTimeout(() => emit("click"), 200);
    }
    return { onClick, internalProcessing };
  },
});
</script>

```

**Comment by posva** [comment] 2020-08-06 07:42
The problem doesn't appear without bootstrap vue, so it must come from the `btnProps`, check the type is correct there, maybe using `{...Button.option.props}` fixes. Closing as the problem is external.

**Closed by posva** 2020-08-06 07:42 UTC
Labels: needs reproduction

**Comment by pikax** [comment] 2020-08-06 07:48
There's no typings for `bootstrap-vue/esm/components/button/button` 

Even with `bootstrap-vue/esm/components/button` it won't work.

The issue is caused by the nonexistent type on `btnProps`, because of that the `props` types cannot be inferred, making them invalid `props`.

**Comment by sadjow** [comment] 2020-08-07 03:49
Thanks a lot @posva and @pikax! 

I am here again just sharing the solution I found in case someone get to this issue later when trying to extend an VueBootstrap component.

```vue
<template lang="pug">
  b-button(v-bind="$props" @click="onClick" :disabled="processing || internalProcessing")
    template(v-if="processing || internalProcessing")
      b-spinner(small)
      |  {{ processingText }}
    template(v-else)
      slot
</template>

<script lang="ts">
import { defineComponent, ref, toRef, watch } from "@vue/composition-api";

import { BButton } from "bootstrap-vue";
// Make a copy of b-button's prop definitions
const btnProps = Object.assign({}, BButton.prototype.$props);

export default defineComponent({
  components: {
    BButton,
  },
  props: {
    ...btnProps,
    processing: {
      type: Boolean,
      default: false,
    },
    processingText: {
      type: String,
      default: "Processing...",
    },
  },
  setup(props, { emit }) {
    const internalProcessing = ref(false);

    const processing = toRef(props, "processing");

    watch(
      () => processing.value,
      (isProcessing) => {
        if (!isProcessing) {
          internalProcessing.value = false;
        }
      }
    );

    function onClick() {
      internalProcessing.value = true;
      setTimeout(() => emit("click"), 200);
    }
    return { onClick, internalProcessing };
  },
});
</script>

```
