### ISSUE TITLE
setup使用getCurrentInstance()返回的对象是null

### ISSUE THREAD

**Issue by seafronthu** [vuejs/composition-api#953] opened 2022-07-12 07:36 UTC
```javascript
setup() {
    alert(1);   // 弹了两次
    const  instance = getCurrentInstance();
    console.log(instance)  // 结果是null 
    // do something
    return {}
}
```
@vue/composition-api版本：1.7.0 （还原到1.4.4正常）
vue版本：2.6.11

**Comment by antfu** [comment] 2022-07-12 07:42
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-12 07:42 UTC
